$(document).ready(function(){
    $('.login').click(function(){
        $('.hover-login-part').toggle();
        $('.hover-login-part').css('transition','1s');
    })
    $('.fa-bars').click(function(){
        $('.toggle-button').slideToggle();
    })
})